[project]
name = "dummy-consensus"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "abstract>=2025.2.17.0",
    "casadi>=3.7.2",
    "matplotlib>=3.10.6",
    "networkx>=3.5",
    "scipy>=1.16.2",
]
